title: Strength Methodology
description: News, posts related to a new approach for software development
show_downloads: true

baseurl: "/Strength-Methodology/" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://chaos-taxi.github.io/Strength-Methodology/" # change this to the base hostname & protocol for your site

google_analytics: UA-128051816-1
# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: "Chaos Taxi | Sebastian Novak | Đorđe Radonić"
image: /thumbnail-jumbo.png
twitter:
  username: chaos-taxi
#  site:
facebook:
  #publisher: 1592372034171500
  #profile_id: 1809805629
  app_id: 1798910940422432 # cayman-blog
  #authors: lorepirri
#  admins:
